name: Check markup links
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install lychee
      run: |
        bash .github/workflows/scripts_new/check_markup_links_1_install.sh
    - name: Run lychee
      run: |
        bash .github/workflows/scripts_new/check_markup_links_2_run.sh
