name: Check markup links
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Check Markup Links
      run: |
        python python/tools/markdown_link_check.py docs
