name: Linters, using linux
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Python check
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/checkout@v4
      - name: Run linters
        run: |
          bash .github/workflows/scripts_new/linters.sh
