name: Linux x86 on-demand
on:
  push:
    branches:
      - main
    branches-ignore:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Linux x86 Build
        run: |
          bash .github/workflows/scripts_new/linux_x86.sh
