name: Linux x86 self-host container on-demand
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: rtx5090
    container:
      image: nvidia/cuda:12.3.1-base-ubuntu22.04
      options: --cpus 12
    steps:
      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git
          git config --global --add safe.directory /__w/taichi/taichi
      - uses: actions/checkout@v4
      - name: Linux x86 Build
        run: |
          bash .github/workflows/scripts_new/linux_x86_container.sh
