name: Mac OS 15 on-demand
on:
  workflow_dispatch:
jobs:
  echo-hello:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Echo Hello
        run: |
          bash .github/workflows/scripts_new/macos_15.sh
