name: Mac OS on-demand
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-15]
    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Mac Build
        run: |
          bash .github/workflows/scripts_new/macos_15.sh
