name: Publish to PyPI
on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'Name of the artifact to download'
        required: true
        type: string
      python_version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.10'
    secrets:
      PYPI_TOKEN:
        required: false

jobs:
  publish_pypi:
    runs-on: ubuntu-24.04
    environment: publish_pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Python check
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: Publish pypi
        run: |
          set -x
          pip install -U pip setuptools twine
          twine --version
          pip --version
          python -c 'import setuptools; print(setuptools.__version__)'
          twine check *.whl
          twine upload --verbose *.whl
