name: Pyright linter
on:
  workflow_call:
    inputs:
      head_ref:
        description: 'The head ref (branch name or PR ref)'
        required: true
        type: string
    secrets:
      AWS_STORAGE_ACCESS_KEY_ID:
        required: true
      AWS_STORAGE_SECRET_ACCESS_KEY:
        required: true
  workflow_dispatch:
jobs:
  build:
    name: Pyright Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_STORAGE_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STORAGE_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Download artifact
        run: |
          set -x
          aws s3 sync s3://genesis-ai-compiler/ci/gstaichi/${GITHUB_SHA:0:7}/cp310/ dist/
      - name: Python check
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install stubs, from wheel, and dev install gstaichi
        run: |
          set -x
          ls -lh dist/
          unzip dist/*.whl -d dist
          mkdir -p stubs/gstaichi/_lib/core
          cp dist/gstaichi/_lib/core/gstaichi_python.pyi stubs/gstaichi/_lib/core/
          touch stubs/gstaichi/_lib/core/py.typed
          pip install setuptools_scm
          pip install -e .
      - name: install torch and pyright
        run: |
          pip install torch pyright
      - name: run pyright
        run: |
          pyright
