name: Pyright linter
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Python check
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Pyright linter
        run: |
          bash .github/workflows/scripts_new/pyright_linter.sh
