name: Pyright linter
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Python check
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed Python files
        id: changed-files
        run: |
            # Get list of modified/added Python files compared to main branch
            # Exclude deleted files (--diff-filter=AM)
            FILES=$(git diff --name-only --diff-filter=AM origin/main...HEAD -- '*.py')
            # Convert newlines to spaces for pyright command
            FILES="${FILES//$'\n'/ }"
            # Store as GitHub Actions output
            echo "files=${FILES}" >> $GITHUB_OUTPUT
      - name: Run pyright linter, against modified files
        run: |
            if [ -n "${{ steps.changed-files.outputs.files }}" ]; then
              bash .github/workflows/scripts_new/pyright_linter.sh ${{ steps.changed-files.outputs.files }}
            else
              echo "No Python files modified - skipping pyright"
            fi
