name: Windows 2025 on-demand
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Python check
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Windows 2025 Build
        run: |
          dir
          ls
          ps
          bash .github/workflows/scripts_new/win.sh
